name: Linting & Formatting

on:
  pull_request_target:

jobs:
  lint:
    name: Check project linting
    runs-on: ubuntu-latest
    steps:
      - name: Disable autoclrf
        run: git config --global core.autocrlf false

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.30.5
      - name: Set up node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check Linting & Formatting
        run: pnpm run lint
