name: UI-Tests
on:
  pull_request:
    branches: [main]

jobs:
  wait_for_preview:
    name: Wait for netlify-preview
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForNetlifyPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Pages changed to neutral
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-Netlify
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          checkName: 'Pages changed'
      - name: Wait for preview-deployment
        uses: josephduffy/wait-for-netlify-action@v1
        id: waitForNetlifyPreviewDeployment
        with:
          site_name: evidence-development-workspace
          max_timeout: 500
          check_interval: 5
  tests:
    name: UI Tests
    needs: wait_for_preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.23.2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile && cd ./tests && npx playwright install --with-deps && pnpm run test:ui
        env:
          BASE_URL: ${{ needs.wait_for_preview.outputs.preview_url }}
